// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaExamenCooperacionAPI.Models;

#nullable disable

namespace PruebaExamenCooperacionAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220218121610_A")]
    partial class A
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.Destinatario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PaisID");

                    b.ToTable("Destinatarios");
                });

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.ODS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("FotoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreOds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Odses");
                });

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.Pais", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BanderaURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.Proyecto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DestinatarioID")
                        .HasColumnType("int");

                    b.Property<int>("OdsID")
                        .HasColumnType("int");

                    b.Property<string>("nombreProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DestinatarioID");

                    b.HasIndex("OdsID");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.Destinatario", b =>
                {
                    b.HasOne("PruebaExamenCooperacionAPI.Models.Pais", "Pais")
                        .WithMany("Destinatarios")
                        .HasForeignKey("PaisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.Proyecto", b =>
                {
                    b.HasOne("PruebaExamenCooperacionAPI.Models.Destinatario", "Destinatario")
                        .WithMany("Proyectos")
                        .HasForeignKey("DestinatarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaExamenCooperacionAPI.Models.ODS", "Ods")
                        .WithMany("Proyectos")
                        .HasForeignKey("OdsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Ods");
                });

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.Destinatario", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.ODS", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("PruebaExamenCooperacionAPI.Models.Pais", b =>
                {
                    b.Navigation("Destinatarios");
                });
#pragma warning restore 612, 618
        }
    }
}
