//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Futbolista
    {
        public Futbolista()
        {
            this.Equipos = new HashSet<Equipo>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Equipo> Equipos { get; set; }
    }
}
